FROM openjdk:8
MAINTAINER zhangdalei<zhangdalei1@jd.com>
RUN apt-get update && apt-get install -y iputils-ping  net-tools


ENV APP_NAME=demo APP_GROUP=v1 PRIVIDER_NAME="-"

WORKDIR /app
COPY target/*.jar /app/app.jar
EXPOSE 80
CMD java ${TRACING_OPTS} -Dserver.port=80 -jar /app/app.jar